### ISSUE TITLE
What happens if one of the processes asks for an input from the user?

### ISSUE THREAD

**Issue by paezao** [tableflip/guvnor#33]
Can I receive an event about that and send the input programatically?

**Comment by achingbrain** [comment]
Do you mean that your process waits for input from stdin?

**Comment by paezao** [comment]
Yes thats what I meant.

**Comment by achingbrain** [comment]
I don't know if you can automatically get notified when something starts listening to stdin, but as of `3.1.0` you can use the [`write`](https://github.com/tableflip/guvnor/blob/1420b34dddb02ccdb32cae23ba1fdf62416a6085/docs/programmatic-access-local.md#write-to-stdin-for-a-process) command to send data to stdin.

For a programatic example, see the [integration test](https://github.com/tableflip/guvnor/blob/1420b34dddb02ccdb32cae23ba1fdf62416a6085/test/integration/GuvnorTest.js#L890-L907) and supporting [test fixture](https://github.com/tableflip/guvnor/blob/1420b34dddb02ccdb32cae23ba1fdf62416a6085/test/integration/fixtures/stdin.js).

**Comment by achingbrain** [comment]
Closing - please reopen if this does not answer your question.
