### ISSUE TITLE
Install fails on io.js 1.1.0

### ISSUE THREAD

**Issue by goloroden** [tableflip/guvnor#34]
When I tried to install boss under io.js 1.1.0, it failed due to the `usage` module. It seems as if its installation [has a bug](https://github.com/arunoda/node-usage/issues/42) with io.js 1.1.0.

Any thoughts on this?

**Comment by achingbrain** [comment]
Hmm, I just pushed a PR that will hopefully resolve this issue: arunoda/node-usage#43 - `usage` now builds and the tests pass on node 0.8, 0.10, 0.12 and io.js 1.1.0 and 1.2.0.

**Comment by goloroden** [comment]
Yes, `usage` has just been published in new version 0.6.0, and this installs fine for me under io.js 1.2.0 :-)

**Comment by achingbrain** [comment]
`boss` 2.6.2 uses `usage` 0.6 - install that and have a go.

All boss unit/integration tests are now passing on io.js 1.1.0 and 1.2.0.

I've observed some weirdness around attaching node inspector to processes (from the boss web UI) as I think the debugging protocol has changed quite a lot in recent versions of v8 but it looks like there's about to be a new node inspector release so hopefully that will clear that up.
