### ISSUE TITLE
Is there a no-daemon mode?

### ISSUE THREAD

**Issue by goloroden** [tableflip/guvnor#39]
E.g., inside of a Docker container, if I want to use `guvnor` as command, then the Docker container exits as soon as the application has been started, since guvnor itself exits.

pm2 has a `--no-daemon` parameter for this.

How do I do this with guvnor?

**Comment by achingbrain** [comment]
Right now it's not possible, sorry!  It's a valid use case though, I'll make sure there's something in a release really soon.

**Comment by goloroden** [comment]
Thanks, that's very nice :-))

**Comment by goloroden** [comment]
Since we need this feature … is there anything we can do to help?

I don't know whether we are able to do it, but could you point out where things need to be done? Then we might create a PR (I can't promise anything, but we at least would like to have a look at it).

**Comment by achingbrain** [comment]
This is in 3.2.0 - there's a [relevant section](https://github.com/tableflip/guvnor#docker) in the readme.

PRs are very gratefully received - please do pitch in if you spot any problems.

**Comment by goloroden** [comment]
Just that I get the point: It's fixed by 3.2.0, but you are still looking for a PR?

Is there anything else that needs to be done before this issue can be closed?

**Comment by achingbrain** [comment]
No, I meant that in general PRs are gratefully received ;)

I think this issue can be closed.  Usually I'd let the opener close it when they feel that the issue has been resolved.
