### ISSUE TITLE
Arguments arent reaching the process

### ISSUE THREAD

**Issue by paezao** [tableflip/guvnor#41]
Im using this syntax but it's not working:

sudo guv start -n ProcessName -a '--username blabla --password blabla --port 3003' app.js

Those arguments aren't getting to the process :(

What am I doing wrong?

**Comment by achingbrain** [comment]
I think this is a bug.  I've just added some integration tests for the CLI, one of which exposes the issue.

There's a fix in master, it'll be in the next release.
