### ISSUE TITLE
guv-web: Restrict User(s) Per Process

### ISSUE THREAD

**Issue by dinosaw** [tableflip/guvnor#47]
Regarding the guv-web interface:

I see the ability to restrict access for users on a per-host/server basis, but not a per-process basis. I would like to see this implemented (or if it's already possible, explain how it is done as I couldn't find anything in the documentation).

Reason being is I run multiple Ghost blogs on a single server, but want multiple users to be able to log into the web interface to restart, check logs, etc of their Ghost blog (or process). As of right now they have access to everyone else's Ghost blog on that same host.

**Comment by achingbrain** [comment]
The intention behind the manager is to be a bit like `ps aux` which lets you see all processes, regardless of user.

Have you considered isolating your processes by running multiple instances of guv under individual Docker containers instead?

**Comment by dinosaw** [comment]
I had thought about it, but didn't want to go that route if I would be able to restrict access per process in Guvnor. However if that is how this application is intended, then I can utilize both it and Docker like you suggested. Thanks.
