### ISSUE TITLE
How to stop ever-crashing guvnor-web?

### ISSUE THREAD

**Issue by goloroden** [tableflip/guvnor#51]
I've set up guvnor and had the (bad) idea to start guvnor-web without first configuring it.

Now I have ended up with a running guvnor-web that starts and crashes immediately. Of course it get's restarted and it crashes again. And so on and so on …

How do I stop this?

If I run

    $ guv stop guvnor-web

I get:

> error: No socket defined

If I try to

    $ guv remove guvnor-web

I get:

> error: Process undefined is still running

If I try to stop the process by its pid, I'd need to capture the correct PID. But since it gets restarted every few milliseconds, I don't have an idea of how to get the correct one.

The only thing I can do is

    $ sudo guv kill

but then everything else is being killed, too. And it still leaves the problem of how to shutdown guvnor-web correctly. If I then run

    $ sudo guv list

again, it's up again, and gets restarted forever :-(

What should I do?

**Comment by gottaloveit** [comment]
same thing, here's what i did

1.service guvnor stop
2. open and edit /etc/guvnor/processes.json
remove the object for guvnor-web
3. service guvnor start

**Comment by goloroden** [comment]
Thanks for that :-)

Anyway, I think (and I don't want to degrade your help, which I really appreciate :-)), that this can only be called a "workaround", not a "solution".

I think there should be an official solution to this problem that should work without the need to stop the entire service and manually editing configuration files.
