### ISSUE TITLE
How do I kill and restart the daemon without launching everything that ran before?

### ISSUE THREAD

**Issue by goloroden** [tableflip/guvnor#52]
If I currently kill guvnor and restart it, all the processes that ran before get started again.

Is there a possibility to avoid this? Something such as a `--no-restart` parameter?

**Comment by achingbrain** [comment]
When guvnor is stopped, remove `/etc/guvnor/processes.json` - this will stop it from starting anything on next start.

If you don't want it to start processes automatically, set the [`autoresume`](https://github.com/tableflip/guvnor/blob/c90814d2f90f3c8470078d183a8b33d067234566/guvnor#L33-L36) property to false in `/etc/guvnor/guvnor`

**Comment by achingbrain** [comment]
Closing because it's been a while.  If you still see a problem, please re-open.
