### ISSUE TITLE
Introduce a process configuration file?

### ISSUE THREAD

**Issue by goloroden** [tableflip/guvnor#54]
In the context of #53 I had the idea, what if there was a project-specific configuration file?

Basically, something such as `guvnor.yml` may be a good idea, similar to CircleCI's `circle.yml` or TravisCI's `travis.yml` that describes things such as which user has access to the project via guvnor, what the limits are (think #53), and possibly other things…

This would have the advantage that configuration is stored with the application, and it is also automatically versioned, backed up and you have a change log.

What do you think about this?

**Comment by olizilla** [comment]
Hi @goloroden, @achingbrain & the @alanshaw are on holiday right now, so there may be some latency on these issues. Keep em' coming though!

**Comment by goloroden** [comment]
Okay, absolutely not a problem, and thanks a lot for pointing that out :-))

(Hope they have nice holidays :-))

**Comment by achingbrain** [comment]
Cross referenced to #66 - pulling process config out of a .guvnor.yml or .guvnorrc in the process's initial cwd would be be quite useful..
