### ISSUE TITLE
cannot install; npm install guvnor --msvs_version=2013

### ISSUE THREAD

**Issue by mike-aungsan** [tableflip/guvnor#56]
Windows Server 2012 Standard Application Server
Microsoft Virtual Studio Community 2013 with Update 4
node -v 2.5.1
npm -v v0.12.0

some errors: 

d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\dns_service_browse.cpp) [D:\photoservice\api\node_modules\guvnor\node_
modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_process_result.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\dns_service_get_addr_info.cpp) [D:\photoservice\api\node_modules\guvno
r\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\dns_service_enumerate_domains.cpp) [D:\photoservice\api\node_modules\g
uvnor\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_ref_deallocate.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\dns_sd.cpp) [D:\photoservice\api\node_modules\guvnor\node_modules\mdns
\build\dns_sd_bindings.vcxproj]
  dns_service_ref_sock_fd.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\dns_service_process_result.cpp) [D:\photoservice\api\node_modules\guvn
or\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_register.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\dns_service_ref_sock_fd.cpp) [D:\photoservice\api\node_modules\guvnor\
node_modules\mdns\build\dns_sd_bindings.vcxproj]
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\dns_service_ref.cpp) [D:\photoservice\api\node_modules\guvnor\node_mod
ules\mdns\build\dns_sd_bindings.vcxproj]
  dns_service_resolve.cpp
  mdns_utils.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\dns_service_ref_deallocate.cpp) [D:\photoservice\api\node_modules\guvn
or\node_modules\mdns\build\dns_sd_bindings.vcxproj]
  network_interface.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\mdns_utils.cpp) [D:\photoservice\api\node_modules\guvnor\node_modules\
mdns\build\dns_sd_bindings.vcxproj]
  socket_watcher.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\dns_service_register.cpp) [D:\photoservice\api\node_modules\guvnor\nod
e_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_ref.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\dns_service_resolve.cpp) [D:\photoservice\api\node_modules\guvnor\node
_modules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_create.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\network_interface.cpp) [D:\photoservice\api\node_modules\guvnor\node_m
odules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_deallocate.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\socket_watcher.cpp) [D:\photoservice\api\node_modules\guvnor\node_modu
les\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_set_value.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\txt_record_create.cpp) [D:\photoservice\api\node_modules\guvnor\node_m
odules\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_get_length.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\txt_record_ref.cpp) [D:\photoservice\api\node_modules\guvnor\node_modu
les\mdns\build\dns_sd_bindings.vcxproj]
  txt_record_buffer_to_object.cpp
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\txt_record_deallocate.cpp) [D:\photoservice\api\node_modules\guvnor\no
de_modules\mdns\build\dns_sd_bindings.vcxproj]
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\txt_record_set_value.cpp) [D:\photoservice\api\node_modules\guvnor\nod
e_modules\mdns\build\dns_sd_bindings.vcxproj]
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\txt_record_buffer_to_object.cpp) [D:\photoservice\api\node_modules\guv
nor\node_modules\mdns\build\dns_sd_bindings.vcxproj]
d:\photoservice\api\node_modules\guvnor\node_modules\mdns\src\mdns.hpp(32): fat
al error C1083: Cannot open include file: 'dns_sd.h': No such file or directory
 (..\src\txt_record_get_length.cpp) [D:\photoservice\api\node_modules\guvnor\no
de_modules\mdns\build\dns_sd_bindings.vcxproj]

**Comment by achingbrain** [comment]
mdns is an optional dependency so those errors would not stop the build process - the thing that killed it is probably later in the logs.

That said guvnor doesn't really support Windows as a platform at the moment as it's heavily dependent on the Unix permissions model for security.

I'm not averse to adding Windows support but it's not something I personally need so it would have to be a pull request.  It'd probably be a case of tracking down use of the [posix](https://www.npmjs.com/package/posix), [etc-passwd](https://www.npmjs.com/package/etc-passwd) modules and friends and isolating them behind some kind of interface.

It'd probably be easier to use [Boot2Docker](https://docs.docker.com/installation/windows/) and deploy it under that.

**Comment by mike-aungsan** [comment]
Many Thanks
