### ISSUE TITLE
Can't start git-installed app in web UI

### ISSUE THREAD

**Issue by randomsock** [tableflip/guvnor#58]
I've installed an app from git using the guv web UI, but when I click on Start, the dialog has a validation error saying "Selection required" immediately below the Group dropdown.  That dropdown is already populated with the default guvnor group, and it doesn't matter if I explicitly select it either, it always says "Selection required".  The Start button then doesn't seem to do anything, and I'm guessing it's because it thinks there's still something missing.
![screenclip](https://cloud.githubusercontent.com/assets/8095654/7122268/3e89a6b6-e212-11e4-8ac6-f0fdb1510af3.png)

**Comment by achingbrain** [comment]
I updated some of the Ampersand modules recently - there's been quite a lot of churn in those projects which may have led to this.

What version of guvnor are you running?

**Comment by randomsock** [comment]
3.5.2

**Comment by randomsock** [comment]
I thought it might be because I messed up the app install first time and seemed to end up with two copies of it, one incomplete.  I cleared everything down and started again cleanly, and it still behaves the same.

**Comment by achingbrain** [comment]
I think this problem was due to the users' primary group not being returned as part of the groups list from guvnor#listUsers.

I've just published 3.5.3 which should resolve this issue - could you give it a go?

**Comment by randomsock** [comment]
Awesome.  Picked up 3.5.4, it lists both my default group and "guvnor", and starts ok now. Thanks.
(BTW, noticed a few other things so I'm probably going to bug you a bit - don't take that badly, I'm trying to get guys at work off pm2 and onto guv, so it'd be good to showcase it).

**Comment by achingbrain** [comment]
No problem - keep the issues coming!
