### ISSUE TITLE
Can't run the same script 2 times and have 2 processes running

### ISSUE THREAD

**Issue by paezao** [tableflip/guvnor#59]
sudo guv start -n 'Project-1' -a 'MY_PARAMETERS' app.js -> This runs okay

sudo guv start -n 'Project-2' -a 'MY_PARAMETERS' app.js
error: Failed to start /Users/USER/Projetos/project/app.js
error:  message=Project is already running

Shouldn't this work?

**Comment by achingbrain** [comment]
That's a bug.  The fix is in v3.5.6.
