### ISSUE TITLE
Web UI start app "Instances" control only allows 1

### ISSUE THREAD

**Issue by randomsock** [tableflip/guvnor#61]
When you start a git-installed app from the UI, the "Instances" is a dropdown and only allows 1.

**Comment by achingbrain** [comment]
How many cores does your server have?

**Comment by randomsock** [comment]
This particular server is a small dev VM so only has 2 cores.

(It varies - we're all virtual now, anything from 2-16 typically, if that helps at all).

**Comment by achingbrain** [comment]
It's a bug.  The fix is in v3.5.7
