### ISSUE TITLE
Installing app from password-protected Stash

### ISSUE THREAD

**Issue by randomsock** [tableflip/guvnor#62]
Access to our corporate Stash is protected.  I tried to use guv-web to install from `https://myusername:stash.repo...` and it hung - I was half-expecting it to prompt me for my password, as it does at a terminal, either that or gracefully fail authentication.

I tried adding my password in the URL, which worked, but it then shows my credentials in plain text on the UI.  I haven't tried this yet, but I'm hoping only I can see that, not other users of the same instance.  Either way, I'm not comfortable with it being visible anywhere.

So:
1. Would it be possible to prompt for a password if the `git clone` failed authentication?
2. Can the credentials be removed from the displayed URL, or at least mask the password ('********')

**Comment by achingbrain** [comment]
Are you able to use SSH URLs and private keys?  If so, set up private key access for the user that installs the app and it should work without you needing to enter any credentials.

**Comment by randomsock** [comment]
Very good point.  Should have thought of that :flushed:  Will give it a go ...

**Comment by randomsock** [comment]
Awesome - yep, SSH is the way to do it, works beautifully.  (Stash lets you add your public key to your own account, without any kind of admin necessary at that end).  Thanks for the suggestion.
