### ISSUE TITLE
"bootstrap-growl" is not in the npm registry

### ISSUE THREAD

**Issue by huygun** [tableflip/guvnor#73]
so guvnor can not be install. 

I think package name change to bootstrap-notify : https://www.npmjs.com/package/bootstrap-notify whit new version...

**Comment by achingbrain** [comment]
Just great. I'm away from the computer right now but have opened an issue on their repo to republish under the old name - mouse0270/bootstrap-notify#102

I'll publish a new version with the updated dependency name as soon as I can.

**Comment by mouse0270** [comment]
I am really sorry about this, I do not use npm. I actually never created nor really updated it. I have asked someone who is more familiar with it and offered to help manage it to look into this for me.

I personally only support meteor and bower. Every other package software out there is being supported by very wonderful people out of the kindness of their hearts. So please be patient as this is looked into.

**Comment by achingbrain** [comment]
v3.5.13 replaces `bootstrap-growl` with `bootstrap-notfiy`.
