### ISSUE TITLE
guvnor doesn't install using node v4

### ISSUE THREAD

**Issue by HERRKIN** [tableflip/guvnor#75]
I tried installing guvnor with the latest node, it throws lots of errors. it wont install.

**Comment by HERRKIN** [comment]
I installed it on the latest iojs and it did install

**Comment by achingbrain** [comment]
I published 3.5.15 which updates some of the native module dependencies to work with node v4.

Weirdly it all seems fine for me with node v4 locally but still explodes on Travis.
