### ISSUE TITLE
[guv-web] "Uncaught TypeError: Invalid data type of `info` for `type` property."

### ISSUE THREAD

**Issue by vuza** [tableflip/guvnor#80]
When we open guv-web in Chrome it asks for username and password and the browser loads the black background, then following error messages gets printed to Google chrome's console:

"Uncaught TypeError: Invalid data type of `info` for `type` property. Use one of the default types or define your own" - guvnor-web.4cc3fb22.min.js:12

Same error on other browsers and with cache cleared.
Guv-web log, looks exactly the same as it does on the servers guv-web works fine. Beside the web-frontend everything works fine as well. Even https://localhost:3001/hosts prints a correct json.

I tried to install it on a virtual server, vagrant machine and locally, and got the same error. Some weeks ago the same guv-web version (tried 3.5.14 and 3.5.15) was running just fine on a identical server.

Any help would be appreciated.

Regards,
Marlon

**Comment by achingbrain** [comment]
Looks like [this change](https://github.com/AmpersandJS/ampersand-state/commit/9e80ea746e9cf80c4f27c0b83e3dacc41137f59a) in ampersand-state may have b0rked it.  I've just published v3.5.16 - please give it a go and reopen this issue if you still see the problem.

**Comment by vuza** [comment]
Works like charm, thank you!!!
