### ISSUE TITLE
group id does not exist?

### ISSUE THREAD

**Issue by mike442144** [tableflip/guvnor#82]
var Local = require('guvnor').Local
Local.connectOrStart(function(error, daemon) {
  if(error) throw error

  daemon.listProcesses(function(error, processes) {
      console.log(processes);
  })
})

This is my code, what should I do?

**Comment by achingbrain** [comment]
Fixed in the gitter channel.  The problem was that the `guvnor` group did not exist.  The solution was to start the daemon from the CLI which does the initial setup.
