### ISSUE TITLE
Install apps from private repositories

### ISSUE THREAD

**Issue by jvictorsoto** [tableflip/guvnor#84]
I tried to install private apps and looks like is possible using the sintax https://user:pwd@repourl
Main problem is that the password is stored plain in the url of the repo, and its even vissible from the web-site. Is there any plan to allow auth in git when installing apps?

**Comment by achingbrain** [comment]
If you configure ssh for the user guvnor runs as to have access to private repos you should be able to use the ssh:// scheme instead of https:// and not have the users' credentials in the url.

**Comment by jvictorsoto** [comment]
Sorry for delay replying, @achingbrain works like a charm.
